version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[cargo]"
      include: scope
    labels:
      - dependencies
      - d:cargo

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[gh-actions]"
      include: scope
    labels:
      - dependencies
      - d:github-actions
