[package]
name = "ghrepo"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
description = "Parse & construct GitHub repository URLs & specifiers"
authors = ["John Thorvald Wodder II <ghrepo@varonathe.org>"]
repository = "https://github.com/jwodder/ghrepo-rust"
license = "MIT"
keywords = ["GitHub", "URL-parsing", "repository"]
categories = ["command-line-utilities"]
exclude = ["/.*"]

[dependencies]
clap = { version = "3.2.8", default-features = false, features = ["derive", "std", "suggestions", "wrap_help"] }
fancy-regex = "0.10.0"
lazy_static = "1.4.0"
serde = "1.0.139"
serde_json = { version = "1.0.82", features = ["preserve_order"] }

[dev-dependencies]
rstest = "0.15.0"
rstest_reuse = "0.4.0"
tempfile = "3.3.0"
which = "4.2.5"
