[package]
name = "ghrepo"
version = "0.3.1"
edition = "2021"
rust-version = "1.60"
description = "Parse & construct GitHub repository URLs & specifiers"
authors = ["John Thorvald Wodder II <ghrepo@varonathe.org>"]
repository = "https://github.com/jwodder/ghrepo-rust"
license = "MIT"
keywords = ["GitHub", "URL-parsing", "repository"]
categories = ["command-line-utilities"]
exclude = ["/.*"]

[dependencies]
lexopt = "0.3.0"

[dev-dependencies]
assert_cmd = "2.0.8"
rstest = { version = "0.16.0", default-features = false }
rstest_reuse = "0.5.0"
tempfile = "3.3.0"
which = "4.4.0"
