name: Check docs

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install nightly Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - name: Activate cache
        uses: Swatinem/rust-cache@v2

      - name: Check docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -Dwarnings

# vim:set et sts=2:
