name: Lint

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustup component add clippy

      - name: Check code
        run: cargo clippy --all-features --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --check

# vim:set et sts=2:
