name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - minimal
          - stable
          - beta
          - nightly
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        # Needed for a couple tests
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'ghactions@nil.nil'

      - name: Install Rust
        if: matrix.toolchain != 'minimal'
        run: |
          rustup update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}

      - name: Install minimal supported Rust
        if: matrix.toolchain == 'minimal'
        run: |
          rust_version="$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].rust_version')"
          rustup update "$rust_version"
          rustup default "$rust_version"

      - name: Test with coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.1'
          args: '--exclude-files "tests/*" --follow-exec'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false

      - name: Install linters
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Check code
        run: cargo clippy --all-features --all-targets -- -Dwarnings

      - name: Check formatting
        run: cargo fmt --check

# vim:set et sts=2:
